backend:
  analytics: null

elasticsearch:
  hosts:
    - "localhost:9200"
    # - "elasticsearch:9200"
  http_auth:
    - "crawler_user_turku"
    - "crawler12345"
  index_prefix: "220113_akaa"
  index_reader_rolename: "turku_index_reader"
  index_writer_rolename: "turku_index_writer"
  languages:
    - fi
    - en
  analyzers:
    default:
      tokenizer:
        "standard"
      token_filters:
        - "lowercase"
    fi:
      stop_stemmer:
        tokenizer:
          "standard"
        token_filters:
          - "lowercase"
          - type: "stop"
            stopwords: "_finnish_"
          - type: "stemmer"
            language: "finnish"
    en:
      stop_stemmer:
        tokenizer:
          "standard"
        token_filters:
          - "lowercase"
          - type: "stop"
            stopwords: "_english_"
          - type: "stemmer"
            language: "english"

  search_settings:
    fuzziness: 0

  suggest_settings: # General settings for the suggest query made from the search backend. 
    suggest1: # Multiple suggestion can be configured if needed - copy this block, rename it and settings
      completion:
        field: "suggest" # Field to search for suggestion in
        skip_duplicates: true
        fuzzy:
          fuzziness: 0
        size: 20 # Amount of suggestions to return

SCRAPY_SETTINGS:
  GENERAL:
    DEPTH_LIMIT: 0
    DOWNLOAD_DELAY: 0.15
    DOWNLOAD_TIMEOUT: 180
    LOG_ENABLED: true
    # LOG_FILE: null
    LOG_FILE: "220113_akaa.log"
    LOG_FORMAT: '%(asctime)s [%(name)s] %(levelname)s: %(message)s'
    LOG_LEVEL: 'INFO'
    LOGSTATS_INTERVAL: 60
    ROBOTSTXT_OBEY: true

  SPIDERS:
    GenericSpider:
      BOT_NAME: "atrsoft"
      ALLOWED_DOMAINS:
        - akaa.fi
      START_URLS:
        - "https://akaa.fi"
      LINK_EXTRACTOR_RULES:
        allow:
        deny:
          - "s="
          - "/eFeedback"
          - "/wp-content/uploads/" 

      CUSTOM_SETTINGS:
        CRAWL_LINKS_ONLY:
          # The pages which have an url containing one of these paths are crawled and links are extracted without indexing the contents.
          # Suitable especially for directory pages or link lists. Value can be empty or null.
          # str | [str] | null

        REPLACE_CHARACTERS:
          # Characters to be replaced with another one within the scraped content. Values set as "key": "value" -pairs. Can be set as empty or null.
          # "the_string_or_character_to_be_replaced": "the_string_to_replace_with_or_an_empty_string_if_removed"
          "\xa0": " "
          " / ": " "

        ITEM_PIPELINES:
          generic.generic.pipelines.ElasticsearchPipeline: 500

        SCRAPER_SETTINGS:
          lang:
            "html"

          head:
            content_to_scrape:
              og:title:
                element: "meta"
                attribute: "og:title"
                attribute-key: "property"
                attribute-value: "content"
                indexing:
                  type: "text"
                  analyzer:
                    fi: "stop_stemmer"
                    sv: "stop_stemmer"
                    en: "stop_stemmer"
                search:
                  boost: 5
                  highlight: true

              og:type:
                element: "meta"
                attribute: "og:type"
                attribute-key: "property"
                attribute-value: "content"

              description:
                element: "meta"
                attribute: "description"
                attribute-key: "name"
                attribute-value: "content"
                indexing:
                  type: "text"
                  analyzer:
                    fi: "stop_stemmer"
                    sv: "stop_stemmer"
                    en: "stop_stemmer"
                search:
                  null

          body:
            element: "div"
            class: "container"
            id: "content"

            exclude_rules:
              valikko:
                element: "aside"
                class: "left-sidebar"
                id: null

            content_to_scrape:
              header1:
                element: "h1"
                attributes:
                  id: null
                  class: null
                indexing:
                  type: "text"
                  analyzer: 
                    fi: "stop_stemmer"
                    sv: "stop_stemmer"
                    en: "stop_stemmer"
                search:
                  boost: 5
                  highlight: true

              header2:
                element: "h2"
                indexing:
                  type: "text"
                  analyzer: 
                    fi: "stop_stemmer"
                    sv: "stop_stemmer"
                    en: "stop_stemmer"
                search:
                  boost: 3
                  highlight: true

              header3:
                element: "h3"
                attributes":
                  id: null
                indexing:
                  type: "text"
                  analyzer:
                    fi: "stop_stemmer"
                    sv: "stop_stemmer"
                    en: "stop_stemmer"
                search:
                  boost: 2
                  highlight: true

              text: 
                element: "div"
                attributes:
                  class: entry-content
                indexing:
                  type: "text"
                  analyzer: 
                    fi: "stop_stemmer"
                    sv: "stop_stemmer"
                    en: "stop_stemmer"
                search:
                  highlight:
                    no_match_size: 100
              
              breadcrumb:
                element: "ul"
                attributes:
                  class: "breadcrumbs"
                search:

        CONTENT_TYPES_AND_THEMES:
          settings: 
            parse_content_type_from: "url" # url / element (breadcrumb or other element inside body where it is!) / datalayer
            parse_themes_from: "breadcrumb" # url / breadcrumb (breadcrumb or element where it is!) / null (if available in e.g. meta tag) / datalayer
            default_content_type: "tietosivu" # if no match below, use this type
            remove_last_part_from_url_path: true # if true, remove the last section from path which is usually the page itself when parsing theme from url or breadcrumb
            remove_first_part_from_breadcrumb: true # if true, remove the first section from breadcrumb (e.g. "Etusivu") when parsing theme from url or breadcrumb
            remove_last_part_from_breadcrumb: true # if true, remove the last section from breadcrumb which is usually the page itself when parsing theme from url or breadcrumb
            display_fields:
              title: 
                default: "Title not found"
                append_values: true
                suggest: false
                index_fields:
                  - "og:title"
              text:
                append_values: false
                suggest: false
                index_fields:
                  - "description"
                  - "full_content"
              publish_date:
                append_values: false
                index_fields:
              modify_date:
                append_values: true
                index_fields:
              writer:
                default:
                suggest: false
                index_fields:
              location:
                suggest: false
                index_fields:
              date: 
                suggest: false
                index_fields:
              time:
                index_fields:
              url:
                index_fields: 
                  - "url"             
              image_url:
                index_fields:
              keywords:
                suggest: false
                index_fields:
              content_type: 
                index_fields:
                  - "content_type"
              themes:             
                suggest: false
                index_fields:
                  - "themes"
          uutinen: # The words below get this content type
            - "uutinen"
            - "uutiset"
          blogi:
            - "blogi"
            - "blogit"
            - "ploki"
          yhteystieto: # The words below get this content type
            - "yhteystieto"
            - "yhteystiedot"
            - "henkilo"
            - "toimipaikka"
            - "toimipiste"
          tapahtuma: # The words below get this content type
            - "tapahtuma"
            - "tapahtumat"
          palvelu_tai_asiointikanava:
            - "palvelu"
            - "asiointikanava"
            - "service"