apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: keha-backend
          image: europe-north1-docker.pkg.dev/turku-keskitetty-hakuratkaisu/keha/search_backend:latest
          args:
            - sh
            - -c
            - /wait && ./start-backend.sh
          env:
            - name: WAIT_HOSTS
              value: elasticsearch:9200
            - name: WAIT_HOSTS_TIMEOUT
              value: "900"
            - name: WAIT_SLEEP_INTERVAL
              value: "10"
            - name: WAIT_HOSTS_CONNECT_TIMEOUT
              value: "30"
            - name: elastic_admin_username
              value: "elastic"
            - name: elastic_admin_password
              value: "epassu12345"
            - name: elastic_write_username
              value: "crawler_user_turku"
            - name: elastic_write_password
              value: "crawler12345"
            - name: elastic_read_username
              value: "backend_user_turku"
            - name: elastic_read_password
              value: "backend12345"
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 300m
              memory: 200Mi
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: backend-loadbalancer
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 80
  selector:
    app: backend
  type: LoadBalancer

---
