apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
        - name: keha-website
          image: europe-north1-docker.pkg.dev/turku-keskitetty-hakuratkaisu/keha/embed_website:latest
          env:
            - name: FOOBAR
              value: foobar
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 50m
              memory: 50Mi
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: website-loadbalancer
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    app: website
  type: LoadBalancer

---
