FROM nginx:alpine
COPY index.html /usr/share/nginx/html
COPY sv.html /usr/share/nginx/html
COPY en.html /usr/share/nginx/html
COPY dev.html /usr/share/nginx/html
COPY style.css /usr/share/nginx/html
COPY full-bundle.js /usr/share/nginx/html
COPY testaus /usr/share/nginx/html/testaus/
EXPOSE 80

